language: ruby
rvm:
- 1.9.3
script: ./_travis/build
bundler_args: --without development --deployment
before_deploy: ./_travis pre_deploy
deploy:
  provider: openshift
  user: candlepinproject
  password:
    secure: AYUZvORwoP5joUq5RPEHJzBNo8mDwjxHxz8LcmbtNMDyaBa4RZgxGrNfdsfhiiRFAYjB0KjTGPvdqLaZ2m/xqDA6ZWAS4aOQROl2q+/RNGtlk6yflozR0YEP24mxjVxbSveAhbGj+R6d5C2/lsudi+a4PvCeV5ldXLDcBF5v4dI=
  app: website
  domain: candlepinproject
  on:
    repo: candlepin/candlepinproject.org
