sudo: false
language: ruby
rvm:
- 2.3.8
before_install:
  - yes | gem update --system --force
  - gem install bundler
  - bundle update --bundler
  - bundle config set deployment 'true'
  - bundle config set without 'development'
branches:
  only:
    - master
addons:
  apt:
    packages:
    - graphviz
    - openjdk-8-jre-headless
script: ./_travis/build
